package model;
// Generated 26.04.2012 16:15:26 by Hibernate Tools 3.2.1.GA



/**
 * Equipment generated by hbm2java
 */
public class Equipment  implements java.io.Serializable {


     private Integer id;
     private Receipt receipt;
     private String name;

    public Equipment() {
    }

    public Equipment(Receipt receipt, String name) {
       this.receipt = receipt;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


